import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import { join, normalize } from 'node:path';
import { Readable } from 'node:stream';
import { NextResponse, type NextRequest } from 'next/server';
import type { ExportRecord } from '@magic/contracts';
import { serverEnv } from '@/shared/lib/env';
import { readSession } from '@/shared/lib/session';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * The download is authorised at the moment of the request and streamed, never buffered.
 *
 * The object key comes from the export record rather than from the URL, and the resolved path is
 * checked to sit inside the export directory — a key that tried to climb out with `..` would
 * otherwise turn a download link into arbitrary file read.
 */
export async function GET(
  _request: NextRequest,
  context: { params: Promise<{ id: string }> },
): Promise<NextResponse> {
  const session = await readSession();
  if (!session) return NextResponse.json({ title: 'Not authenticated', status: 401 }, { status: 401 });

  const { id } = await context.params;
  const env = serverEnv();

  const response = await fetch(`${env.API_INTERNAL_URL}/v1/exports/${id}`, {
    headers: {
      'x-service-token': env.SERVICE_TOKEN,
      'x-magic-tenant-id': session.tenant.id,
      'x-magic-role': session.role,
      ...(session.user.id ? { 'x-magic-user-id': session.user.id } : {}),
    },
    cache: 'no-store',
  });

  if (!response.ok) {
    return NextResponse.json({ title: 'Not found', status: 404 }, { status: 404 });
  }

  const record = (await response.json()) as ExportRecord & { object_key?: string };
  if (record.status !== 'ready') {
    return NextResponse.json({ title: 'Not ready', status: 409, detail: 'This export is not ready yet.' }, { status: 409 });
  }

  const objectKey = `exports/${session.tenant.id}/${id}.${record.format}`;
  const root = normalize(env.EXPORT_DIR);
  const filePath = normalize(join(root, objectKey));

  if (!filePath.startsWith(root)) {
    return NextResponse.json({ title: 'Not found', status: 404 }, { status: 404 });
  }

  try {
    const info = await stat(filePath);
    const stream = Readable.toWeb(createReadStream(filePath)) as ReadableStream;

    return new NextResponse(stream, {
      headers: {
        'content-type': record.format === 'csv' ? 'text/csv; charset=utf-8' : 'application/octet-stream',
        'content-length': String(info.size),
        'content-disposition': `attachment; filename="magic-${record.kind}-${id}.${record.format}"`,
        'cache-control': 'no-store',
      },
    });
  } catch {
    /**
     * The file is generated by the worker and read here, so the two must share a filesystem.
     * They do under Docker Compose, which mounts one volume into both. They do not on a platform
     * where each service gets its own disk, and the honest answer there is that this deployment
     * has no shared export storage rather than that the file expired — the two have different
     * fixes, and reporting the wrong one sends whoever reads it looking in the wrong place.
     */
    const shared = env.EXPORT_STORAGE_SHARED;
    return NextResponse.json(
      shared
        ? { title: 'Not found', status: 404, detail: 'The generated file is no longer available.' }
        : {
            title: 'Exports not available',
            status: 501,
            detail:
              'This deployment has no shared export storage, so a generated file cannot be served. ' +
              'Exports need an object store before they work here.',
          },
      { status: shared ? 404 : 501 },
    );
  }
}
